id: P006980
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:08.681399
source_metadata:
  id: bdr:W21943
  title: བོན་གྱི་ཐ་སྙད་རིག་གནས་བསྟན་བཅོས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    693b5119e57e45e1bd8b324e1a3ab7c1:
      image_group_id: I1GS54236
      title: Volume 1 of bon gyi tha snyad rig gnas bstan bcos phyogs bsgrigs
      volume_number: 1
      total_pages: 301
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
